version: "3.9"
services:
  db:
    container_name: getgo-pg
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: getgo-pg
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    container_name: getgo-api
    ports:
      - "3003:3003"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  data:
